namespace NetworkingCore
{
    public enum MessageTypes
    {
        Connected,
        Disconnect,
        Generic,
        AttachEnergyToBench,
        DiscardCards,
        DeckSearch,
        PickFromList,
        SelectColor,
        SelectFromOpponentBench,
        GameUpdate,
        SelectFromYourBench,
        SelectOpponentPokemon,
        SelectPriceCards,
        GameLogReload,
        GameLogNewMessages,
        SelectFromYourPokemon,
        YesNoMessage,
        Error,
        GameOver,
        Ping,
        CardListMessage,
        Info,
        GameEvent,
    }
}
