namespace NetworkingCore
{
    public enum MessageTypes
    {
        Connected,
        Disconnect,
        Generic,
        AttachEnergyToBench,
        DiscardCards,
        DeckSearch,
        PickFromList,
        SelectColor,
        SelectFromOpponentBench,
        GameUpdate,
        SelectFromYourBench,
        SelectOpponentPokemon,
        SelectPrizeCards,
        GameLogReload,
        GameLogNewMessages,
        SelectFromYourPokemon,
        YesNoMessage,
        Error,
        GameOver,
        Ping,
        CardListMessage,
        Info,
        GameEvent,
        SelectAttack,
        SelectedAttack,
        RevealCardsMessage,
        SelectStatus,
        StatusSelected,
    }
}
