//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using TCGCards;
        ///using TCGCards.Core;
        ///
        ///namespace {SETNAME}.Attacks
        ///{
        ///    internal class {CLASSNAME} : Attack
        ///    {
        ///        public {CLASSNAME}()
        ///        {
        ///            Name = &quot;{NAME}&quot;;
        ///            Description = {DESCRIPTION};
        ///            Cost = new List&lt;Energy&gt;
        ///            {
        ///                {COST}
        ///            };
        ///        }
        ///
        ///
        ///        public override int GetDamage(Player owner, Player opponent)
        ///        {
        ///            return {DAMAGE};
        ///        }
        ///
        ///		{NEEDSMORE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttackTemplate {
            get {
                return ResourceManager.GetString("AttackTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using TCGCards;
        ///using TCGCards.Core;
        ///using TeamRocket.Attacks;
        ///
        ///namespace {SETNAME}.PokemonCards
        ///{
        ///    public class {CLASSNAME} : IPokemonCard
        ///    {
        ///        public {CLASSNAME}(Player owner) : base(owner)
        ///        {
        ///            PokemonName = {NAME};
        ///			{EVOLVESFROM}
        ///            Hp = {HP};
        ///            PokemonType = {TYPE};
        ///            RetreatCost = {RETREAT};
        ///            Weakness = {WEAKNESS};
        ///			Resistence = {RESISTENCE};
        ///            Attacks = new List&lt;Attac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PokemonTemplate {
            get {
                return ResourceManager.GetString("PokemonTemplate", resourceCulture);
            }
        }
    }
}
